# 回测配置文件

# 基础设置
backtest:
  # 初始资金
  cash: 100000
  # 手续费率
  commission: 0.001
  # 滑点
  slippage: 0.0005
  # 回测开始日期
  start_date: '2020-01-01'
  # 回测结束日期
  end_date: '2023-12-31'

# 数据源配置
data:
  # 数据源类型: yahoo, ccxt, csv
  source: 'yahoo'
  # 数据频率: 1d, 1h, 5m, 1m
  timeframe: '1d'
  # 股票代码列表
  symbols:
    - 'AAPL'
    - 'MSFT'
    - 'GOOGL'
  # 数据存储路径
  data_path: './data/'

# 策略配置
strategy:
  # 策略名称
  name: 'SimpleMovingAverageStrategy'
  # 策略参数
  params:
    fast_period: 10
    slow_period: 30
    stop_loss: 0.05
    take_profit: 0.15

# 分析器配置
analyzers:
  # 是否启用各种分析器
  sharpe_ratio: true
  drawdown: true
  returns: true
  trades: true
  positions: true

# 输出配置
output:
  # 是否显示图表
  plot: true
  # 是否保存结果
  save_results: true
  # 结果保存路径
  results_path: './results/'
  # 日志级别
  log_level: 'INFO'

# 风险管理
risk:
  # 最大持仓比例
  max_position_size: 0.1
  # 最大回撤限制
  max_drawdown: 0.2
  # 单笔交易最大风险
  max_risk_per_trade: 0.02