analyzers:
  drawdown: true
  returns: true
  sharpe_ratio: true
  trades: true
backtest:
  cash: 100000
  commission: 0.001
  end_date: '2023-12-31'
  slippage: 0.0005
  start_date: '2022-01-01'
data:
  data_path: ./data/
  source: yahoo
  symbols:
  - AAPL
  - MSFT
  timeframe: 1d
output:
  log_level: INFO
  plot: false
  results_path: ./results/
  save_results: true
strategy:
  name: SimpleMovingAverageStrategy
  params:
    fast_period: 10
    slow_period: 30
    stop_loss: 0.05
    take_profit: 0.15
